name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v6
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  test:
    strategy:
      fail-fast: false
      matrix:
        jdk: [ adopt@1.8, adopt@1.11, adopt@1.14 ]
        scala: [ 2.13.5, 2.12.13, 2.11.12 ]
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdk }}
      - uses: coursier/cache-action@v6
      - name: sbt test
        run: sbt -v ++${{ matrix.scala }} test
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 111016
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - id: changed
        run: |
          TARGET_FILES=(".scalafmt.conf", "project/plugins.sbt", "project/Dependencies.scala")
          readarray -d ',' -t CHANGED_FILES <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          echo ${CHANGED_FILES[@]}
          EXIST="false"
          for CHANGED_FILE in ${CHANGED_FILES[@]}; do
            CHANGED_FILE=$(echo $CHANGED_FILE | sed -e 's/,//')
            echo "CHANGED_FILE=$CHANGED_FILE"
            for TARGET_FILE in ${TARGET_FILES[@]}; do
              echo "TARGET_FILE=$TARGET_FILE"
              if [[ ${CHANGED_FILE} = ${TARGET_FILE} ]]; then
                echo "EXIST=true; break; loop = 1"
                EXIST="true"
                break
              fi
            done
            if [[ "$EXIST" = "true" ]]; then
                echo "EXIST=true; break; loop = 2"
              break
            fi
          done
          echo "result = $EXIST"
          echo "::set-output name=result::$EXIST"
      - name: labeler
        uses: actions/labeler@v3
        with:
          repo-token: "${{ steps.generate_token.outputs.token }}"
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_FILTER_AUTHOR: "j5ik2o-bot[bot]"
